[package]
name = "rusty-TicTacToe"
version = "0.1.0"
edition = "2021"

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

[profile.release]
lto = "thin"
opt-level = 's'


[dependencies]
regex = "1"
bevy = "0.7"